### ISSUE TITLE
art spec push bug

### ISSUE THREAD

**Issue by ghost** [gatblau/onix#95]
Hi Gatblau!

Was using your Artisan CLI in a project but came across a bug that seems to have been introduced sometime after the 22nd February(as far as I can tell!)

`art spec push -c myname:mypassword s3s://my3scloud.com/abc/1.0.0 -t docker.my.stack -i`

In previous versions this worked, but in the latest versions I get this as it starts to process the first docker image:

`2022/03/04 06:41:03.388065 ART ERROR: cannot push spec - exec: "tag": executable file not found in $PATH`

**Comment by gatblau** [comment]
fixed in commit 18f22eccf1db95903dfc23d4d22a26bf14e81b33
